[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tapcardkz"
version = "0.1.0"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "sqlalchemy>=2.0",
  "asyncpg",
  "alembic",
  "pydantic>=2.0",
  "pydantic-settings",
  "python-dotenv",
]

[tool.setuptools]
packages = ["app"]
